application: feedmerger
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: /.*
  script: index.py
